/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.CoachTeam;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoachTeamRecord extends TableRecordImpl<CoachTeamRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1311772612;

    /**
     * Setter for <code>testdb3.coach_team.coachID</code>.
     */
    public void setCoachid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.coach_team.coachID</code>.
     */
    public String getCoachid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb3.coach_team.teamID</code>.
     */
    public void setTeamid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.coach_team.teamID</code>.
     */
    public String getTeamid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CoachTeam.COACH_TEAM.COACHID;
    }

    @Override
    public Field<String> field2() {
        return CoachTeam.COACH_TEAM.TEAMID;
    }

    @Override
    public String component1() {
        return getCoachid();
    }

    @Override
    public String component2() {
        return getTeamid();
    }

    @Override
    public String value1() {
        return getCoachid();
    }

    @Override
    public String value2() {
        return getTeamid();
    }

    @Override
    public CoachTeamRecord value1(String value) {
        setCoachid(value);
        return this;
    }

    @Override
    public CoachTeamRecord value2(String value) {
        setTeamid(value);
        return this;
    }

    @Override
    public CoachTeamRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoachTeamRecord
     */
    public CoachTeamRecord() {
        super(CoachTeam.COACH_TEAM);
    }

    /**
     * Create a detached, initialised CoachTeamRecord
     */
    public CoachTeamRecord(String coachid, String teamid) {
        super(CoachTeam.COACH_TEAM);

        set(0, coachid);
        set(1, teamid);
    }
}
