/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.Eventrecorder;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventrecorderRecord extends UpdatableRecordImpl<EventrecorderRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1317380078;

    /**
     * Setter for <code>demodb.eventrecorder.matchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.eventrecorder.matchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Eventrecorder.EVENTRECORDER.MATCHID;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public EventrecorderRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public EventrecorderRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventrecorderRecord
     */
    public EventrecorderRecord() {
        super(Eventrecorder.EVENTRECORDER);
    }

    /**
     * Create a detached, initialised EventrecorderRecord
     */
    public EventrecorderRecord(Integer matchid) {
        super(Eventrecorder.EVENTRECORDER);

        set(0, matchid);
    }
}
