/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.EventsrecorderEvents;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsrecorderEventsRecord extends TableRecordImpl<EventsrecorderEventsRecord> implements Record4<Integer, String, Integer, String> {

    private static final long serialVersionUID = 1786696344;

    /**
     * Setter for <code>localsoccer.eventsrecorder_events.matchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>localsoccer.eventsrecorder_events.matchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>localsoccer.eventsrecorder_events.time</code>.
     */
    public void setTime(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>localsoccer.eventsrecorder_events.time</code>.
     */
    public String getTime() {
        return (String) get(1);
    }

    /**
     * Setter for <code>localsoccer.eventsrecorder_events.eventID</code>.
     */
    public void setEventid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>localsoccer.eventsrecorder_events.eventID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>localsoccer.eventsrecorder_events.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>localsoccer.eventsrecorder_events.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EventsrecorderEvents.EVENTSRECORDER_EVENTS.MATCHID;
    }

    @Override
    public Field<String> field2() {
        return EventsrecorderEvents.EVENTSRECORDER_EVENTS.TIME;
    }

    @Override
    public Field<Integer> field3() {
        return EventsrecorderEvents.EVENTSRECORDER_EVENTS.EVENTID;
    }

    @Override
    public Field<String> field4() {
        return EventsrecorderEvents.EVENTSRECORDER_EVENTS.TYPE;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public String component2() {
        return getTime();
    }

    @Override
    public Integer component3() {
        return getEventid();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public String value2() {
        return getTime();
    }

    @Override
    public Integer value3() {
        return getEventid();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public EventsrecorderEventsRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public EventsrecorderEventsRecord value2(String value) {
        setTime(value);
        return this;
    }

    @Override
    public EventsrecorderEventsRecord value3(Integer value) {
        setEventid(value);
        return this;
    }

    @Override
    public EventsrecorderEventsRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public EventsrecorderEventsRecord values(Integer value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsrecorderEventsRecord
     */
    public EventsrecorderEventsRecord() {
        super(EventsrecorderEvents.EVENTSRECORDER_EVENTS);
    }

    /**
     * Create a detached, initialised EventsrecorderEventsRecord
     */
    public EventsrecorderEventsRecord(Integer matchid, String time, Integer eventid, String type) {
        super(EventsrecorderEvents.EVENTSRECORDER_EVENTS);

        set(0, matchid);
        set(1, time);
        set(2, eventid);
        set(3, type);
    }
}
