/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.Goal;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoalRecord extends TableRecordImpl<GoalRecord> implements Record6<Integer, Integer, String, String, String, Boolean> {

    private static final long serialVersionUID = 763334010;

    /**
     * Setter for <code>demodb.goal.MatchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.goal.MatchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.goal.EventID</code>.
     */
    public void setEventid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.goal.EventID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>demodb.goal.Time</code>.
     */
    public void setTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>demodb.goal.Time</code>.
     */
    public String getTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>demodb.goal.PlayerGoalID</code>.
     */
    public void setPlayergoalid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>demodb.goal.PlayerGoalID</code>.
     */
    public String getPlayergoalid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>demodb.goal.PlayerAssistID</code>.
     */
    public void setPlayerassistid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>demodb.goal.PlayerAssistID</code>.
     */
    public String getPlayerassistid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>demodb.goal.isOwnGoal</code>.
     */
    public void setIsowngoal(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>demodb.goal.isOwnGoal</code>.
     */
    public Boolean getIsowngoal() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, String, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Goal.GOAL.MATCHID;
    }

    @Override
    public Field<Integer> field2() {
        return Goal.GOAL.EVENTID;
    }

    @Override
    public Field<String> field3() {
        return Goal.GOAL.TIME;
    }

    @Override
    public Field<String> field4() {
        return Goal.GOAL.PLAYERGOALID;
    }

    @Override
    public Field<String> field5() {
        return Goal.GOAL.PLAYERASSISTID;
    }

    @Override
    public Field<Boolean> field6() {
        return Goal.GOAL.ISOWNGOAL;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public Integer component2() {
        return getEventid();
    }

    @Override
    public String component3() {
        return getTime();
    }

    @Override
    public String component4() {
        return getPlayergoalid();
    }

    @Override
    public String component5() {
        return getPlayerassistid();
    }

    @Override
    public Boolean component6() {
        return getIsowngoal();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public Integer value2() {
        return getEventid();
    }

    @Override
    public String value3() {
        return getTime();
    }

    @Override
    public String value4() {
        return getPlayergoalid();
    }

    @Override
    public String value5() {
        return getPlayerassistid();
    }

    @Override
    public Boolean value6() {
        return getIsowngoal();
    }

    @Override
    public GoalRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public GoalRecord value2(Integer value) {
        setEventid(value);
        return this;
    }

    @Override
    public GoalRecord value3(String value) {
        setTime(value);
        return this;
    }

    @Override
    public GoalRecord value4(String value) {
        setPlayergoalid(value);
        return this;
    }

    @Override
    public GoalRecord value5(String value) {
        setPlayerassistid(value);
        return this;
    }

    @Override
    public GoalRecord value6(Boolean value) {
        setIsowngoal(value);
        return this;
    }

    @Override
    public GoalRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoalRecord
     */
    public GoalRecord() {
        super(Goal.GOAL);
    }

    /**
     * Create a detached, initialised GoalRecord
     */
    public GoalRecord(Integer matchid, Integer eventid, String time, String playergoalid, String playerassistid, Boolean isowngoal) {
        super(Goal.GOAL);

        set(0, matchid);
        set(1, eventid);
        set(2, time);
        set(3, playergoalid);
        set(4, playerassistid);
        set(5, isowngoal);
    }
}
