/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.MatchFollowers;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchFollowersRecord extends TableRecordImpl<MatchFollowersRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 2031054774;

    /**
     * Setter for <code>demodb.match_followers.matchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.match_followers.matchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.match_followers.followerID</code>.
     */
    public void setFollowerid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.match_followers.followerID</code>.
     */
    public String getFollowerid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MatchFollowers.MATCH_FOLLOWERS.MATCHID;
    }

    @Override
    public Field<String> field2() {
        return MatchFollowers.MATCH_FOLLOWERS.FOLLOWERID;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public String component2() {
        return getFollowerid();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public String value2() {
        return getFollowerid();
    }

    @Override
    public MatchFollowersRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public MatchFollowersRecord value2(String value) {
        setFollowerid(value);
        return this;
    }

    @Override
    public MatchFollowersRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchFollowersRecord
     */
    public MatchFollowersRecord() {
        super(MatchFollowers.MATCH_FOLLOWERS);
    }

    /**
     * Create a detached, initialised MatchFollowersRecord
     */
    public MatchFollowersRecord(Integer matchid, String followerid) {
        super(MatchFollowers.MATCH_FOLLOWERS);

        set(0, matchid);
        set(1, followerid);
    }
}
