/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.Match;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchRecord extends UpdatableRecordImpl<MatchRecord> implements Record11<Integer, String, Integer, String, String, String, String, UByte, LocalDate, Integer, String> {

    private static final long serialVersionUID = -1788837454;

    /**
     * Setter for <code>demodb.match.MatchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.match.MatchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.match.LeagueID</code>.
     */
    public void setLeagueid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.match.LeagueID</code>.
     */
    public String getLeagueid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demodb.match.SeasonID</code>.
     */
    public void setSeasonid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>demodb.match.SeasonID</code>.
     */
    public Integer getSeasonid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>demodb.match.TeamHomeID</code>.
     */
    public void setTeamhomeid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>demodb.match.TeamHomeID</code>.
     */
    public String getTeamhomeid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>demodb.match.TeamAwayID</code>.
     */
    public void setTeamawayid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>demodb.match.TeamAwayID</code>.
     */
    public String getTeamawayid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>demodb.match.StadiumID</code>.
     */
    public void setStadiumid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>demodb.match.StadiumID</code>.
     */
    public String getStadiumid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>demodb.match.Score</code>.
     */
    public void setScore(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>demodb.match.Score</code>.
     */
    public String getScore() {
        return (String) get(6);
    }

    /**
     * Setter for <code>demodb.match.isFinished</code>.
     */
    public void setIsfinished(UByte value) {
        set(7, value);
    }

    /**
     * Getter for <code>demodb.match.isFinished</code>.
     */
    public UByte getIsfinished() {
        return (UByte) get(7);
    }

    /**
     * Setter for <code>demodb.match.Date</code>.
     */
    public void setDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>demodb.match.Date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>demodb.match.numberOfFans</code>.
     */
    public void setNumberoffans(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>demodb.match.numberOfFans</code>.
     */
    public Integer getNumberoffans() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>demodb.match.mainRefereeID</code>.
     */
    public void setMainrefereeid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>demodb.match.mainRefereeID</code>.
     */
    public String getMainrefereeid() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, Integer, String, String, String, String, UByte, LocalDate, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, Integer, String, String, String, String, UByte, LocalDate, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Match.MATCH.MATCHID;
    }

    @Override
    public Field<String> field2() {
        return Match.MATCH.LEAGUEID;
    }

    @Override
    public Field<Integer> field3() {
        return Match.MATCH.SEASONID;
    }

    @Override
    public Field<String> field4() {
        return Match.MATCH.TEAMHOMEID;
    }

    @Override
    public Field<String> field5() {
        return Match.MATCH.TEAMAWAYID;
    }

    @Override
    public Field<String> field6() {
        return Match.MATCH.STADIUMID;
    }

    @Override
    public Field<String> field7() {
        return Match.MATCH.SCORE;
    }

    @Override
    public Field<UByte> field8() {
        return Match.MATCH.ISFINISHED;
    }

    @Override
    public Field<LocalDate> field9() {
        return Match.MATCH.DATE;
    }

    @Override
    public Field<Integer> field10() {
        return Match.MATCH.NUMBEROFFANS;
    }

    @Override
    public Field<String> field11() {
        return Match.MATCH.MAINREFEREEID;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public String component2() {
        return getLeagueid();
    }

    @Override
    public Integer component3() {
        return getSeasonid();
    }

    @Override
    public String component4() {
        return getTeamhomeid();
    }

    @Override
    public String component5() {
        return getTeamawayid();
    }

    @Override
    public String component6() {
        return getStadiumid();
    }

    @Override
    public String component7() {
        return getScore();
    }

    @Override
    public UByte component8() {
        return getIsfinished();
    }

    @Override
    public LocalDate component9() {
        return getDate();
    }

    @Override
    public Integer component10() {
        return getNumberoffans();
    }

    @Override
    public String component11() {
        return getMainrefereeid();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public String value2() {
        return getLeagueid();
    }

    @Override
    public Integer value3() {
        return getSeasonid();
    }

    @Override
    public String value4() {
        return getTeamhomeid();
    }

    @Override
    public String value5() {
        return getTeamawayid();
    }

    @Override
    public String value6() {
        return getStadiumid();
    }

    @Override
    public String value7() {
        return getScore();
    }

    @Override
    public UByte value8() {
        return getIsfinished();
    }

    @Override
    public LocalDate value9() {
        return getDate();
    }

    @Override
    public Integer value10() {
        return getNumberoffans();
    }

    @Override
    public String value11() {
        return getMainrefereeid();
    }

    @Override
    public MatchRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public MatchRecord value2(String value) {
        setLeagueid(value);
        return this;
    }

    @Override
    public MatchRecord value3(Integer value) {
        setSeasonid(value);
        return this;
    }

    @Override
    public MatchRecord value4(String value) {
        setTeamhomeid(value);
        return this;
    }

    @Override
    public MatchRecord value5(String value) {
        setTeamawayid(value);
        return this;
    }

    @Override
    public MatchRecord value6(String value) {
        setStadiumid(value);
        return this;
    }

    @Override
    public MatchRecord value7(String value) {
        setScore(value);
        return this;
    }

    @Override
    public MatchRecord value8(UByte value) {
        setIsfinished(value);
        return this;
    }

    @Override
    public MatchRecord value9(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public MatchRecord value10(Integer value) {
        setNumberoffans(value);
        return this;
    }

    @Override
    public MatchRecord value11(String value) {
        setMainrefereeid(value);
        return this;
    }

    @Override
    public MatchRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, UByte value8, LocalDate value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchRecord
     */
    public MatchRecord() {
        super(Match.MATCH);
    }

    /**
     * Create a detached, initialised MatchRecord
     */
    public MatchRecord(Integer matchid, String leagueid, Integer seasonid, String teamhomeid, String teamawayid, String stadiumid, String score, UByte isfinished, LocalDate date, Integer numberoffans, String mainrefereeid) {
        super(Match.MATCH);

        set(0, matchid);
        set(1, leagueid);
        set(2, seasonid);
        set(3, teamhomeid);
        set(4, teamawayid);
        set(5, stadiumid);
        set(6, score);
        set(7, isfinished);
        set(8, date);
        set(9, numberoffans);
        set(10, mainrefereeid);
    }
}
