/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.MatchReferee;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchRefereeRecord extends TableRecordImpl<MatchRefereeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 854551966;

    /**
     * Setter for <code>demodb.match_referee.MatchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.match_referee.MatchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.match_referee.RefereeID</code>.
     */
    public void setRefereeid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.match_referee.RefereeID</code>.
     */
    public String getRefereeid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MatchReferee.MATCH_REFEREE.MATCHID;
    }

    @Override
    public Field<String> field2() {
        return MatchReferee.MATCH_REFEREE.REFEREEID;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public String component2() {
        return getRefereeid();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public String value2() {
        return getRefereeid();
    }

    @Override
    public MatchRefereeRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public MatchRefereeRecord value2(String value) {
        setRefereeid(value);
        return this;
    }

    @Override
    public MatchRefereeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchRefereeRecord
     */
    public MatchRefereeRecord() {
        super(MatchReferee.MATCH_REFEREE);
    }

    /**
     * Create a detached, initialised MatchRefereeRecord
     */
    public MatchRefereeRecord(Integer matchid, String refereeid) {
        super(MatchReferee.MATCH_REFEREE);

        set(0, matchid);
        set(1, refereeid);
    }
}
