/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.OwnerTeams;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnerTeamsRecord extends TableRecordImpl<OwnerTeamsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1506931196;

    /**
     * Setter for <code>localsoccer.owner_teams.OwnerID</code>.
     */
    public void setOwnerid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>localsoccer.owner_teams.OwnerID</code>.
     */
    public String getOwnerid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>localsoccer.owner_teams.teamID</code>.
     */
    public void setTeamid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>localsoccer.owner_teams.teamID</code>.
     */
    public String getTeamid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OwnerTeams.OWNER_TEAMS.OWNERID;
    }

    @Override
    public Field<String> field2() {
        return OwnerTeams.OWNER_TEAMS.TEAMID;
    }

    @Override
    public String component1() {
        return getOwnerid();
    }

    @Override
    public String component2() {
        return getTeamid();
    }

    @Override
    public String value1() {
        return getOwnerid();
    }

    @Override
    public String value2() {
        return getTeamid();
    }

    @Override
    public OwnerTeamsRecord value1(String value) {
        setOwnerid(value);
        return this;
    }

    @Override
    public OwnerTeamsRecord value2(String value) {
        setTeamid(value);
        return this;
    }

    @Override
    public OwnerTeamsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OwnerTeamsRecord
     */
    public OwnerTeamsRecord() {
        super(OwnerTeams.OWNER_TEAMS);
    }

    /**
     * Create a detached, initialised OwnerTeamsRecord
     */
    public OwnerTeamsRecord(String ownerid, String teamid) {
        super(OwnerTeams.OWNER_TEAMS);

        set(0, ownerid);
        set(1, teamid);
    }
}
