/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.PageFollowers;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageFollowersRecord extends TableRecordImpl<PageFollowersRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1295700906;

    /**
     * Setter for <code>demodb.page_followers.pageID</code>.
     */
    public void setPageid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.page_followers.pageID</code>.
     */
    public Integer getPageid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.page_followers.followerID</code>.
     */
    public void setFollowerid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.page_followers.followerID</code>.
     */
    public String getFollowerid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PageFollowers.PAGE_FOLLOWERS.PAGEID;
    }

    @Override
    public Field<String> field2() {
        return PageFollowers.PAGE_FOLLOWERS.FOLLOWERID;
    }

    @Override
    public Integer component1() {
        return getPageid();
    }

    @Override
    public String component2() {
        return getFollowerid();
    }

    @Override
    public Integer value1() {
        return getPageid();
    }

    @Override
    public String value2() {
        return getFollowerid();
    }

    @Override
    public PageFollowersRecord value1(Integer value) {
        setPageid(value);
        return this;
    }

    @Override
    public PageFollowersRecord value2(String value) {
        setFollowerid(value);
        return this;
    }

    @Override
    public PageFollowersRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PageFollowersRecord
     */
    public PageFollowersRecord() {
        super(PageFollowers.PAGE_FOLLOWERS);
    }

    /**
     * Create a detached, initialised PageFollowersRecord
     */
    public PageFollowersRecord(Integer pageid, String followerid) {
        super(PageFollowers.PAGE_FOLLOWERS);

        set(0, pageid);
        set(1, followerid);
    }
}
