/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.PagePost;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * all posts of username
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagePostRecord extends TableRecordImpl<PagePostRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1468553688;

    /**
     * Setter for <code>testdb3.page_post.pageID</code>.
     */
    public void setPageid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.page_post.pageID</code>.
     */
    public Integer getPageid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>testdb3.page_post.post</code>.
     */
    public void setPost(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.page_post.post</code>.
     */
    public String getPost() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PagePost.PAGE_POST.PAGEID;
    }

    @Override
    public Field<String> field2() {
        return PagePost.PAGE_POST.POST;
    }

    @Override
    public Integer component1() {
        return getPageid();
    }

    @Override
    public String component2() {
        return getPost();
    }

    @Override
    public Integer value1() {
        return getPageid();
    }

    @Override
    public String value2() {
        return getPost();
    }

    @Override
    public PagePostRecord value1(Integer value) {
        setPageid(value);
        return this;
    }

    @Override
    public PagePostRecord value2(String value) {
        setPost(value);
        return this;
    }

    @Override
    public PagePostRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PagePostRecord
     */
    public PagePostRecord() {
        super(PagePost.PAGE_POST);
    }

    /**
     * Create a detached, initialised PagePostRecord
     */
    public PagePostRecord(Integer pageid, String post) {
        super(PagePost.PAGE_POST);

        set(0, pageid);
        set(1, post);
    }
}
