/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.PreviousGamesInStadium;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PreviousGamesInStadiumRecord extends TableRecordImpl<PreviousGamesInStadiumRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 771814252;

    /**
     * Setter for <code>testdb3.previous_games_in_stadium.StadiumID</code>.
     */
    public void setStadiumid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.previous_games_in_stadium.StadiumID</code>.
     */
    public String getStadiumid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb3.previous_games_in_stadium.MatchID</code>.
     */
    public void setMatchid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.previous_games_in_stadium.MatchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM.STADIUMID;
    }

    @Override
    public Field<Integer> field2() {
        return PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM.MATCHID;
    }

    @Override
    public String component1() {
        return getStadiumid();
    }

    @Override
    public Integer component2() {
        return getMatchid();
    }

    @Override
    public String value1() {
        return getStadiumid();
    }

    @Override
    public Integer value2() {
        return getMatchid();
    }

    @Override
    public PreviousGamesInStadiumRecord value1(String value) {
        setStadiumid(value);
        return this;
    }

    @Override
    public PreviousGamesInStadiumRecord value2(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public PreviousGamesInStadiumRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PreviousGamesInStadiumRecord
     */
    public PreviousGamesInStadiumRecord() {
        super(PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM);
    }

    /**
     * Create a detached, initialised PreviousGamesInStadiumRecord
     */
    public PreviousGamesInStadiumRecord(String stadiumid, Integer matchid) {
        super(PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM);

        set(0, stadiumid);
        set(1, matchid);
    }
}
