/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.Redcard;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedcardRecord extends TableRecordImpl<RedcardRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -794300370;

    /**
     * Setter for <code>demodb.redcard.MatchID</code>.
     */
    public void setMatchid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.redcard.MatchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.redcard.EventID</code>.
     */
    public void setEventid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.redcard.EventID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>demodb.redcard.Time</code>.
     */
    public void setTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>demodb.redcard.Time</code>.
     */
    public String getTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>demodb.redcard.PlayerAgainstID</code>.
     */
    public void setPlayeragainstid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>demodb.redcard.PlayerAgainstID</code>.
     */
    public String getPlayeragainstid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Redcard.REDCARD.MATCHID;
    }

    @Override
    public Field<Integer> field2() {
        return Redcard.REDCARD.EVENTID;
    }

    @Override
    public Field<String> field3() {
        return Redcard.REDCARD.TIME;
    }

    @Override
    public Field<String> field4() {
        return Redcard.REDCARD.PLAYERAGAINSTID;
    }

    @Override
    public Integer component1() {
        return getMatchid();
    }

    @Override
    public Integer component2() {
        return getEventid();
    }

    @Override
    public String component3() {
        return getTime();
    }

    @Override
    public String component4() {
        return getPlayeragainstid();
    }

    @Override
    public Integer value1() {
        return getMatchid();
    }

    @Override
    public Integer value2() {
        return getEventid();
    }

    @Override
    public String value3() {
        return getTime();
    }

    @Override
    public String value4() {
        return getPlayeragainstid();
    }

    @Override
    public RedcardRecord value1(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public RedcardRecord value2(Integer value) {
        setEventid(value);
        return this;
    }

    @Override
    public RedcardRecord value3(String value) {
        setTime(value);
        return this;
    }

    @Override
    public RedcardRecord value4(String value) {
        setPlayeragainstid(value);
        return this;
    }

    @Override
    public RedcardRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RedcardRecord
     */
    public RedcardRecord() {
        super(Redcard.REDCARD);
    }

    /**
     * Create a detached, initialised RedcardRecord
     */
    public RedcardRecord(Integer matchid, Integer eventid, String time, String playeragainstid) {
        super(Redcard.REDCARD);

        set(0, matchid);
        set(1, eventid);
        set(2, time);
        set(3, playeragainstid);
    }
}
