/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.RefereeMatches;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeMatchesRecord extends TableRecordImpl<RefereeMatchesRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -1310288126;

    /**
     * Setter for <code>testdb3.referee_matches.refereeID</code>.
     */
    public void setRefereeid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.referee_matches.refereeID</code>.
     */
    public String getRefereeid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb3.referee_matches.matchID</code>.
     */
    public void setMatchid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.referee_matches.matchID</code>.
     */
    public Integer getMatchid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RefereeMatches.REFEREE_MATCHES.REFEREEID;
    }

    @Override
    public Field<Integer> field2() {
        return RefereeMatches.REFEREE_MATCHES.MATCHID;
    }

    @Override
    public String component1() {
        return getRefereeid();
    }

    @Override
    public Integer component2() {
        return getMatchid();
    }

    @Override
    public String value1() {
        return getRefereeid();
    }

    @Override
    public Integer value2() {
        return getMatchid();
    }

    @Override
    public RefereeMatchesRecord value1(String value) {
        setRefereeid(value);
        return this;
    }

    @Override
    public RefereeMatchesRecord value2(Integer value) {
        setMatchid(value);
        return this;
    }

    @Override
    public RefereeMatchesRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereeMatchesRecord
     */
    public RefereeMatchesRecord() {
        super(RefereeMatches.REFEREE_MATCHES);
    }

    /**
     * Create a detached, initialised RefereeMatchesRecord
     */
    public RefereeMatchesRecord(String refereeid, Integer matchid) {
        super(RefereeMatches.REFEREE_MATCHES);

        set(0, refereeid);
        set(1, matchid);
    }
}
