/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.SeasonReferee;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeasonRefereeRecord extends TableRecordImpl<SeasonRefereeRecord> implements Record3<String, Integer, String> {

    private static final long serialVersionUID = 892561233;

    /**
     * Setter for <code>testdb3.season_referee.LeagueID</code>.
     */
    public void setLeagueid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.season_referee.LeagueID</code>.
     */
    public String getLeagueid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb3.season_referee.SeasonID</code>.
     */
    public void setSeasonid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.season_referee.SeasonID</code>.
     */
    public Integer getSeasonid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>testdb3.season_referee.RefereeID</code>.
     */
    public void setRefereeid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb3.season_referee.RefereeID</code>.
     */
    public String getRefereeid() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SeasonReferee.SEASON_REFEREE.LEAGUEID;
    }

    @Override
    public Field<Integer> field2() {
        return SeasonReferee.SEASON_REFEREE.SEASONID;
    }

    @Override
    public Field<String> field3() {
        return SeasonReferee.SEASON_REFEREE.REFEREEID;
    }

    @Override
    public String component1() {
        return getLeagueid();
    }

    @Override
    public Integer component2() {
        return getSeasonid();
    }

    @Override
    public String component3() {
        return getRefereeid();
    }

    @Override
    public String value1() {
        return getLeagueid();
    }

    @Override
    public Integer value2() {
        return getSeasonid();
    }

    @Override
    public String value3() {
        return getRefereeid();
    }

    @Override
    public SeasonRefereeRecord value1(String value) {
        setLeagueid(value);
        return this;
    }

    @Override
    public SeasonRefereeRecord value2(Integer value) {
        setSeasonid(value);
        return this;
    }

    @Override
    public SeasonRefereeRecord value3(String value) {
        setRefereeid(value);
        return this;
    }

    @Override
    public SeasonRefereeRecord values(String value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeasonRefereeRecord
     */
    public SeasonRefereeRecord() {
        super(SeasonReferee.SEASON_REFEREE);
    }

    /**
     * Create a detached, initialised SeasonRefereeRecord
     */
    public SeasonRefereeRecord(String leagueid, Integer seasonid, String refereeid) {
        super(SeasonReferee.SEASON_REFEREE);

        set(0, leagueid);
        set(1, seasonid);
        set(2, refereeid);
    }
}
