/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.SeasonTableleague;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeasonTableleagueRecord extends TableRecordImpl<SeasonTableleagueRecord> implements Record7<String, Integer, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -758385616;

    /**
     * Setter for <code>testdb3.season_tableleague.LeagueID</code>.
     */
    public void setLeagueid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.LeagueID</code>.
     */
    public String getLeagueid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb3.season_tableleague.SeasonID</code>.
     */
    public void setSeasonid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.SeasonID</code>.
     */
    public Integer getSeasonid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>testdb3.season_tableleague.TeamID</code>.
     */
    public void setTeamid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.TeamID</code>.
     */
    public String getTeamid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>testdb3.season_tableleague.numOfGames</code>.
     */
    public void setNumofgames(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.numOfGames</code>.
     */
    public Integer getNumofgames() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>testdb3.season_tableleague.goalsFor</code>.
     */
    public void setGoalsfor(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.goalsFor</code>.
     */
    public Integer getGoalsfor() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>testdb3.season_tableleague.goalsAgainst</code>.
     */
    public void setGoalsagainst(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.goalsAgainst</code>.
     */
    public Integer getGoalsagainst() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>testdb3.season_tableleague.Points</code>.
     */
    public void setPoints(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>testdb3.season_tableleague.Points</code>.
     */
    public Integer getPoints() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Integer, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SeasonTableleague.SEASON_TABLELEAGUE.LEAGUEID;
    }

    @Override
    public Field<Integer> field2() {
        return SeasonTableleague.SEASON_TABLELEAGUE.SEASONID;
    }

    @Override
    public Field<String> field3() {
        return SeasonTableleague.SEASON_TABLELEAGUE.TEAMID;
    }

    @Override
    public Field<Integer> field4() {
        return SeasonTableleague.SEASON_TABLELEAGUE.NUMOFGAMES;
    }

    @Override
    public Field<Integer> field5() {
        return SeasonTableleague.SEASON_TABLELEAGUE.GOALSFOR;
    }

    @Override
    public Field<Integer> field6() {
        return SeasonTableleague.SEASON_TABLELEAGUE.GOALSAGAINST;
    }

    @Override
    public Field<Integer> field7() {
        return SeasonTableleague.SEASON_TABLELEAGUE.POINTS;
    }

    @Override
    public String component1() {
        return getLeagueid();
    }

    @Override
    public Integer component2() {
        return getSeasonid();
    }

    @Override
    public String component3() {
        return getTeamid();
    }

    @Override
    public Integer component4() {
        return getNumofgames();
    }

    @Override
    public Integer component5() {
        return getGoalsfor();
    }

    @Override
    public Integer component6() {
        return getGoalsagainst();
    }

    @Override
    public Integer component7() {
        return getPoints();
    }

    @Override
    public String value1() {
        return getLeagueid();
    }

    @Override
    public Integer value2() {
        return getSeasonid();
    }

    @Override
    public String value3() {
        return getTeamid();
    }

    @Override
    public Integer value4() {
        return getNumofgames();
    }

    @Override
    public Integer value5() {
        return getGoalsfor();
    }

    @Override
    public Integer value6() {
        return getGoalsagainst();
    }

    @Override
    public Integer value7() {
        return getPoints();
    }

    @Override
    public SeasonTableleagueRecord value1(String value) {
        setLeagueid(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord value2(Integer value) {
        setSeasonid(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord value3(String value) {
        setTeamid(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord value4(Integer value) {
        setNumofgames(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord value5(Integer value) {
        setGoalsfor(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord value6(Integer value) {
        setGoalsagainst(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord value7(Integer value) {
        setPoints(value);
        return this;
    }

    @Override
    public SeasonTableleagueRecord values(String value1, Integer value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeasonTableleagueRecord
     */
    public SeasonTableleagueRecord() {
        super(SeasonTableleague.SEASON_TABLELEAGUE);
    }

    /**
     * Create a detached, initialised SeasonTableleagueRecord
     */
    public SeasonTableleagueRecord(String leagueid, Integer seasonid, String teamid, Integer numofgames, Integer goalsfor, Integer goalsagainst, Integer points) {
        super(SeasonTableleague.SEASON_TABLELEAGUE);

        set(0, leagueid);
        set(1, seasonid);
        set(2, teamid);
        set(3, numofgames);
        set(4, goalsfor);
        set(5, goalsagainst);
        set(6, points);
    }
}
