/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.Teams;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamsRecord extends UpdatableRecordImpl<TeamsRecord> implements Record5<String, Integer, Boolean, String, Boolean> {

    private static final long serialVersionUID = -2099022400;

    /**
     * Setter for <code>demodb.teams.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.teams.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>demodb.teams.establishedYear</code>.
     */
    public void setEstablishedyear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.teams.establishedYear</code>.
     */
    public Integer getEstablishedyear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>demodb.teams.isActive</code>.
     */
    public void setIsactive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>demodb.teams.isActive</code>.
     */
    public Boolean getIsactive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>demodb.teams.teamManagerID</code>.
     */
    public void setTeammanagerid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>demodb.teams.teamManagerID</code>.
     */
    public String getTeammanagerid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>demodb.teams.closedByAdmin</code>.
     */
    public void setClosedbyadmin(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>demodb.teams.closedByAdmin</code>.
     */
    public Boolean getClosedbyadmin() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Integer, Boolean, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, Integer, Boolean, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Teams.TEAMS.NAME;
    }

    @Override
    public Field<Integer> field2() {
        return Teams.TEAMS.ESTABLISHEDYEAR;
    }

    @Override
    public Field<Boolean> field3() {
        return Teams.TEAMS.ISACTIVE;
    }

    @Override
    public Field<String> field4() {
        return Teams.TEAMS.TEAMMANAGERID;
    }

    @Override
    public Field<Boolean> field5() {
        return Teams.TEAMS.CLOSEDBYADMIN;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public Integer component2() {
        return getEstablishedyear();
    }

    @Override
    public Boolean component3() {
        return getIsactive();
    }

    @Override
    public String component4() {
        return getTeammanagerid();
    }

    @Override
    public Boolean component5() {
        return getClosedbyadmin();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public Integer value2() {
        return getEstablishedyear();
    }

    @Override
    public Boolean value3() {
        return getIsactive();
    }

    @Override
    public String value4() {
        return getTeammanagerid();
    }

    @Override
    public Boolean value5() {
        return getClosedbyadmin();
    }

    @Override
    public TeamsRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public TeamsRecord value2(Integer value) {
        setEstablishedyear(value);
        return this;
    }

    @Override
    public TeamsRecord value3(Boolean value) {
        setIsactive(value);
        return this;
    }

    @Override
    public TeamsRecord value4(String value) {
        setTeammanagerid(value);
        return this;
    }

    @Override
    public TeamsRecord value5(Boolean value) {
        setClosedbyadmin(value);
        return this;
    }

    @Override
    public TeamsRecord values(String value1, Integer value2, Boolean value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsRecord
     */
    public TeamsRecord() {
        super(Teams.TEAMS);
    }

    /**
     * Create a detached, initialised TeamsRecord
     */
    public TeamsRecord(String name, Integer establishedyear, Boolean isactive, String teammanagerid, Boolean closedbyadmin) {
        super(Teams.TEAMS);

        set(0, name);
        set(1, establishedyear);
        set(2, isactive);
        set(3, teammanagerid);
        set(4, closedbyadmin);
    }
}
