/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.TeamownerOwnereligible;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamownerOwnereligibleRecord extends UpdatableRecordImpl<TeamownerOwnereligibleRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -603106931;

    /**
     * Setter for <code>localsoccer.teamowner_ownereligible.OwnerID</code>.
     */
    public void setOwnerid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>localsoccer.teamowner_ownereligible.OwnerID</code>.
     */
    public String getOwnerid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>localsoccer.teamowner_ownereligible.playerID</code>.
     */
    public void setPlayerid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>localsoccer.teamowner_ownereligible.playerID</code>.
     */
    public String getPlayerid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>localsoccer.teamowner_ownereligible.managerID</code>.
     */
    public void setManagerid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>localsoccer.teamowner_ownereligible.managerID</code>.
     */
    public String getManagerid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>localsoccer.teamowner_ownereligible.coachID</code>.
     */
    public void setCoachid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>localsoccer.teamowner_ownereligible.coachID</code>.
     */
    public String getCoachid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.OWNERID;
    }

    @Override
    public Field<String> field2() {
        return TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.PLAYERID;
    }

    @Override
    public Field<String> field3() {
        return TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.MANAGERID;
    }

    @Override
    public Field<String> field4() {
        return TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.COACHID;
    }

    @Override
    public String component1() {
        return getOwnerid();
    }

    @Override
    public String component2() {
        return getPlayerid();
    }

    @Override
    public String component3() {
        return getManagerid();
    }

    @Override
    public String component4() {
        return getCoachid();
    }

    @Override
    public String value1() {
        return getOwnerid();
    }

    @Override
    public String value2() {
        return getPlayerid();
    }

    @Override
    public String value3() {
        return getManagerid();
    }

    @Override
    public String value4() {
        return getCoachid();
    }

    @Override
    public TeamownerOwnereligibleRecord value1(String value) {
        setOwnerid(value);
        return this;
    }

    @Override
    public TeamownerOwnereligibleRecord value2(String value) {
        setPlayerid(value);
        return this;
    }

    @Override
    public TeamownerOwnereligibleRecord value3(String value) {
        setManagerid(value);
        return this;
    }

    @Override
    public TeamownerOwnereligibleRecord value4(String value) {
        setCoachid(value);
        return this;
    }

    @Override
    public TeamownerOwnereligibleRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamownerOwnereligibleRecord
     */
    public TeamownerOwnereligibleRecord() {
        super(TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE);
    }

    /**
     * Create a detached, initialised TeamownerOwnereligibleRecord
     */
    public TeamownerOwnereligibleRecord(String ownerid, String playerid, String managerid, String coachid) {
        super(TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE);

        set(0, ownerid);
        set(1, playerid);
        set(2, managerid);
        set(3, coachid);
    }
}
