/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables.records;


import dataLayer.Tables.tables.TeamPlayers;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamPlayersRecord extends TableRecordImpl<TeamPlayersRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -6127856;

    /**
     * Setter for <code>testdb3.team_players.teamID</code>.
     */
    public void setTeamid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb3.team_players.teamID</code>.
     */
    public String getTeamid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb3.team_players.PlayerID</code>.
     */
    public void setPlayerid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb3.team_players.PlayerID</code>.
     */
    public String getPlayerid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TeamPlayers.TEAM_PLAYERS.TEAMID;
    }

    @Override
    public Field<String> field2() {
        return TeamPlayers.TEAM_PLAYERS.PLAYERID;
    }

    @Override
    public String component1() {
        return getTeamid();
    }

    @Override
    public String component2() {
        return getPlayerid();
    }

    @Override
    public String value1() {
        return getTeamid();
    }

    @Override
    public String value2() {
        return getPlayerid();
    }

    @Override
    public TeamPlayersRecord value1(String value) {
        setTeamid(value);
        return this;
    }

    @Override
    public TeamPlayersRecord value2(String value) {
        setPlayerid(value);
        return this;
    }

    @Override
    public TeamPlayersRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamPlayersRecord
     */
    public TeamPlayersRecord() {
        super(TeamPlayers.TEAM_PLAYERS);
    }

    /**
     * Create a detached, initialised TeamPlayersRecord
     */
    public TeamPlayersRecord(String teamid, String playerid) {
        super(TeamPlayers.TEAM_PLAYERS);

        set(0, teamid);
        set(1, playerid);
    }
}
