/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables;


import dataLayer.Tables.tables.CoachTeam;
import dataLayer.Tables.tables.EventsrecorderEvents;
import dataLayer.Tables.tables.Foul;
import dataLayer.Tables.tables.Goal;
import dataLayer.Tables.tables.Injury;
import dataLayer.Tables.tables.MatchReferee;
import dataLayer.Tables.tables.Offside;
import dataLayer.Tables.tables.OwnerManagerAssignings;
import dataLayer.Tables.tables.OwnerOwnerAssignings;
import dataLayer.Tables.tables.OwnerTeams;
import dataLayer.Tables.tables.PageOwner;
import dataLayer.Tables.tables.PagePost;
import dataLayer.Tables.tables.Players;
import dataLayer.Tables.tables.PreviousGamesInStadium;
import dataLayer.Tables.tables.Redcard;
import dataLayer.Tables.tables.RefereeMatches;
import dataLayer.Tables.tables.SeasonMatches;
import dataLayer.Tables.tables.SeasonReferee;
import dataLayer.Tables.tables.SeasonTableleague;
import dataLayer.Tables.tables.SeasonTeams;
import dataLayer.Tables.tables.Seasons;
import dataLayer.Tables.tables.Substitute;
import dataLayer.Tables.tables.TeamPlayers;
import dataLayer.Tables.tables.TeamownerOwnereligible;
import dataLayer.Tables.tables.Yellowcard;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>demodb</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COACH_TEAM_COACHID = Indexes0.COACH_TEAM_COACHID;
    public static final Index EVENTSRECORDER_EVENTS_EVENTID = Indexes0.EVENTSRECORDER_EVENTS_EVENTID;
    public static final Index EVENTSRECORDER_EVENTS_MATCHID = Indexes0.EVENTSRECORDER_EVENTS_MATCHID;
    public static final Index FOUL_MATCHID = Indexes0.FOUL_MATCHID;
    public static final Index GOAL_MATCHID = Indexes0.GOAL_MATCHID;
    public static final Index INJURY_MATCHID = Indexes0.INJURY_MATCHID;
    public static final Index MATCH_REFEREE_MATCHID = Indexes0.MATCH_REFEREE_MATCHID;
    public static final Index OFFSIDE_MATCHID = Indexes0.OFFSIDE_MATCHID;
    public static final Index OWNER_MANAGER_ASSIGNINGS_OWNERID = Indexes0.OWNER_MANAGER_ASSIGNINGS_OWNERID;
    public static final Index OWNER_OWNER_ASSIGNINGS_OWNERID = Indexes0.OWNER_OWNER_ASSIGNINGS_OWNERID;
    public static final Index OWNER_TEAMS_OWNERID = Indexes0.OWNER_TEAMS_OWNERID;
    public static final Index PAGE_OWNER_OWNERID = Indexes0.PAGE_OWNER_OWNERID;
    public static final Index PAGE_OWNER_PAGEID = Indexes0.PAGE_OWNER_PAGEID;
    public static final Index PAGE_POST_USERNAMEID = Indexes0.PAGE_POST_USERNAMEID;
    public static final Index PLAYERS_TEAMOWNERFICTIVE = Indexes0.PLAYERS_TEAMOWNERFICTIVE;
    public static final Index PREVIOUS_GAMES_IN_STADIUM_STADIUMID = Indexes0.PREVIOUS_GAMES_IN_STADIUM_STADIUMID;
    public static final Index REDCARD_MATCHID = Indexes0.REDCARD_MATCHID;
    public static final Index REFEREE_MATCHES_REFEREEID = Indexes0.REFEREE_MATCHES_REFEREEID;
    public static final Index SEASON_MATCHES_LEAGUEID = Indexes0.SEASON_MATCHES_LEAGUEID;
    public static final Index SEASON_REFEREE_LEAGUEID_SEASONID = Indexes0.SEASON_REFEREE_LEAGUEID_SEASONID;
    public static final Index SEASON_TABLELEAGUE_LEAGUEID = Indexes0.SEASON_TABLELEAGUE_LEAGUEID;
    public static final Index SEASON_TEAMS_LEAGUEID = Indexes0.SEASON_TEAMS_LEAGUEID;
    public static final Index SEASONS_LEAGUEID = Indexes0.SEASONS_LEAGUEID;
    public static final Index SEASONS_SEASONID = Indexes0.SEASONS_SEASONID;
    public static final Index SUBSTITUTE_MATCHID = Indexes0.SUBSTITUTE_MATCHID;
    public static final Index TEAM_PLAYERS_TEAMID = Indexes0.TEAM_PLAYERS_TEAMID;
    public static final Index TEAMOWNER_OWNERELIGIBLE_COACHID = Indexes0.TEAMOWNER_OWNERELIGIBLE_COACHID;
    public static final Index TEAMOWNER_OWNERELIGIBLE_MANAGERID = Indexes0.TEAMOWNER_OWNERELIGIBLE_MANAGERID;
    public static final Index TEAMOWNER_OWNERELIGIBLE_PLAYERID = Indexes0.TEAMOWNER_OWNERELIGIBLE_PLAYERID;
    public static final Index YELLOWCARD_MATCHID = Indexes0.YELLOWCARD_MATCHID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COACH_TEAM_COACHID = Internal.createIndex("coachID", CoachTeam.COACH_TEAM, new OrderField[] { CoachTeam.COACH_TEAM.COACHID }, false);
        public static Index EVENTSRECORDER_EVENTS_EVENTID = Internal.createIndex("eventID", EventsrecorderEvents.EVENTSRECORDER_EVENTS, new OrderField[] { EventsrecorderEvents.EVENTSRECORDER_EVENTS.EVENTID }, false);
        public static Index EVENTSRECORDER_EVENTS_MATCHID = Internal.createIndex("matchID", EventsrecorderEvents.EVENTSRECORDER_EVENTS, new OrderField[] { EventsrecorderEvents.EVENTSRECORDER_EVENTS.MATCHID }, false);
        public static Index FOUL_MATCHID = Internal.createIndex("MatchID", Foul.FOUL, new OrderField[] { Foul.FOUL.MATCHID }, false);
        public static Index GOAL_MATCHID = Internal.createIndex("MatchID", Goal.GOAL, new OrderField[] { Goal.GOAL.MATCHID }, false);
        public static Index INJURY_MATCHID = Internal.createIndex("MatchID", Injury.INJURY, new OrderField[] { Injury.INJURY.MATCHID }, false);
        public static Index MATCH_REFEREE_MATCHID = Internal.createIndex("MatchID", MatchReferee.MATCH_REFEREE, new OrderField[] { MatchReferee.MATCH_REFEREE.MATCHID }, false);
        public static Index OFFSIDE_MATCHID = Internal.createIndex("MatchID", Offside.OFFSIDE, new OrderField[] { Offside.OFFSIDE.MATCHID }, false);
        public static Index OWNER_MANAGER_ASSIGNINGS_OWNERID = Internal.createIndex("ownerID", OwnerManagerAssignings.OWNER_MANAGER_ASSIGNINGS, new OrderField[] { OwnerManagerAssignings.OWNER_MANAGER_ASSIGNINGS.OWNERID }, false);
        public static Index OWNER_OWNER_ASSIGNINGS_OWNERID = Internal.createIndex("ownerID", OwnerOwnerAssignings.OWNER_OWNER_ASSIGNINGS, new OrderField[] { OwnerOwnerAssignings.OWNER_OWNER_ASSIGNINGS.OWNERID }, false);
        public static Index OWNER_TEAMS_OWNERID = Internal.createIndex("OwnerID", OwnerTeams.OWNER_TEAMS, new OrderField[] { OwnerTeams.OWNER_TEAMS.OWNERID }, false);
        public static Index PAGE_OWNER_OWNERID = Internal.createIndex("ownerID", PageOwner.PAGE_OWNER, new OrderField[] { PageOwner.PAGE_OWNER.OWNERID }, false);
        public static Index PAGE_OWNER_PAGEID = Internal.createIndex("pageID", PageOwner.PAGE_OWNER, new OrderField[] { PageOwner.PAGE_OWNER.PAGEID }, false);
        public static Index PAGE_POST_USERNAMEID = Internal.createIndex("usernameID", PagePost.PAGE_POST, new OrderField[] { PagePost.PAGE_POST.PAGEID }, false);
        public static Index PLAYERS_TEAMOWNERFICTIVE = Internal.createIndex("teamOwnerfictive", Players.PLAYERS, new OrderField[] { Players.PLAYERS.TEAMOWNERID_FICTIVE }, false);
        public static Index PREVIOUS_GAMES_IN_STADIUM_STADIUMID = Internal.createIndex("StadiumID", PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM, new OrderField[] { PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM.STADIUMID }, false);
        public static Index REDCARD_MATCHID = Internal.createIndex("MatchID", Redcard.REDCARD, new OrderField[] { Redcard.REDCARD.MATCHID }, false);
        public static Index REFEREE_MATCHES_REFEREEID = Internal.createIndex("refereeID", RefereeMatches.REFEREE_MATCHES, new OrderField[] { RefereeMatches.REFEREE_MATCHES.REFEREEID }, false);
        public static Index SEASON_MATCHES_LEAGUEID = Internal.createIndex("LeagueID", SeasonMatches.SEASON_MATCHES, new OrderField[] { SeasonMatches.SEASON_MATCHES.LEAGUEID }, false);
        public static Index SEASON_REFEREE_LEAGUEID_SEASONID = Internal.createIndex("LeagueID_SeasonID", SeasonReferee.SEASON_REFEREE, new OrderField[] { SeasonReferee.SEASON_REFEREE.LEAGUEID, SeasonReferee.SEASON_REFEREE.SEASONID }, false);
        public static Index SEASON_TABLELEAGUE_LEAGUEID = Internal.createIndex("LeagueID", SeasonTableleague.SEASON_TABLELEAGUE, new OrderField[] { SeasonTableleague.SEASON_TABLELEAGUE.LEAGUEID }, false);
        public static Index SEASON_TEAMS_LEAGUEID = Internal.createIndex("LeagueID", SeasonTeams.SEASON_TEAMS, new OrderField[] { SeasonTeams.SEASON_TEAMS.LEAGUEID }, false);
        public static Index SEASONS_LEAGUEID = Internal.createIndex("leagueID", Seasons.SEASONS, new OrderField[] { Seasons.SEASONS.LEAGUEID }, false);
        public static Index SEASONS_SEASONID = Internal.createIndex("seasonID", Seasons.SEASONS, new OrderField[] { Seasons.SEASONS.SEASONID }, false);
        public static Index SUBSTITUTE_MATCHID = Internal.createIndex("MatchID", Substitute.SUBSTITUTE, new OrderField[] { Substitute.SUBSTITUTE.MATCHID }, false);
        public static Index TEAM_PLAYERS_TEAMID = Internal.createIndex("teamID", TeamPlayers.TEAM_PLAYERS, new OrderField[] { TeamPlayers.TEAM_PLAYERS.TEAMID }, false);
        public static Index TEAMOWNER_OWNERELIGIBLE_COACHID = Internal.createIndex("coachID", TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE, new OrderField[] { TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.COACHID }, false);
        public static Index TEAMOWNER_OWNERELIGIBLE_MANAGERID = Internal.createIndex("managerID", TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE, new OrderField[] { TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.MANAGERID }, false);
        public static Index TEAMOWNER_OWNERELIGIBLE_PLAYERID = Internal.createIndex("playerID", TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE, new OrderField[] { TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE.PLAYERID }, false);
        public static Index YELLOWCARD_MATCHID = Internal.createIndex("MatchID", Yellowcard.YELLOWCARD, new OrderField[] { Yellowcard.YELLOWCARD.MATCHID }, false);
    }
}
