/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables;


import dataLayer.Tables.tables.Admins;
import dataLayer.Tables.tables.ApprovalRequests;
import dataLayer.Tables.tables.Ars;
import dataLayer.Tables.tables.CoachTeam;
import dataLayer.Tables.tables.Coaches;
import dataLayer.Tables.tables.Complaints;
import dataLayer.Tables.tables.Eventrecorder;
import dataLayer.Tables.tables.EventsrecorderEvents;
import dataLayer.Tables.tables.Fans;
import dataLayer.Tables.tables.Foul;
import dataLayer.Tables.tables.Goal;
import dataLayer.Tables.tables.Injury;
import dataLayer.Tables.tables.League;
import dataLayer.Tables.tables.Match;
import dataLayer.Tables.tables.MatchReferee;
import dataLayer.Tables.tables.MatchingPolicy;
import dataLayer.Tables.tables.Offside;
import dataLayer.Tables.tables.OwnerManagerAssignings;
import dataLayer.Tables.tables.OwnerOwnerAssignings;
import dataLayer.Tables.tables.OwnerTeams;
import dataLayer.Tables.tables.OwnersOfStadium;
import dataLayer.Tables.tables.PagePost;
import dataLayer.Tables.tables.Pages;
import dataLayer.Tables.tables.Players;
import dataLayer.Tables.tables.PreviousGamesInStadium;
import dataLayer.Tables.tables.Rankingpolicy;
import dataLayer.Tables.tables.Redcard;
import dataLayer.Tables.tables.RefereeMatches;
import dataLayer.Tables.tables.Referees;
import dataLayer.Tables.tables.SeasonMatches;
import dataLayer.Tables.tables.SeasonReferee;
import dataLayer.Tables.tables.SeasonTableleague;
import dataLayer.Tables.tables.SeasonTeams;
import dataLayer.Tables.tables.Seasons;
import dataLayer.Tables.tables.Stadium;
import dataLayer.Tables.tables.Subscribers;
import dataLayer.Tables.tables.Substitute;
import dataLayer.Tables.tables.TeamPlayers;
import dataLayer.Tables.tables.Teammanagers;
import dataLayer.Tables.tables.TeamownerOwnereligible;
import dataLayer.Tables.tables.Teams;
import dataLayer.Tables.tables.UnconfirmedTeams;
import dataLayer.Tables.tables.Yellowcard;


/**
 * Convenience access to all tables in localsoccer
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>localsoccer.admins</code>.
     */
    public static final Admins ADMINS = Admins.ADMINS;

    /**
     * The table <code>localsoccer.approval_requests</code>.
     */
    public static final ApprovalRequests APPROVAL_REQUESTS = ApprovalRequests.APPROVAL_REQUESTS;

    /**
     * The table <code>localsoccer.ars</code>.
     */
    public static final Ars ARS = Ars.ARS;

    /**
     * The table <code>localsoccer.coach_team</code>.
     */
    public static final CoachTeam COACH_TEAM = CoachTeam.COACH_TEAM;

    /**
     * The table <code>localsoccer.coaches</code>.
     */
    public static final Coaches COACHES = Coaches.COACHES;

    /**
     * The table <code>localsoccer.complaints</code>.
     */
    public static final Complaints COMPLAINTS = Complaints.COMPLAINTS;

    /**
     * The table <code>localsoccer.eventrecorder</code>.
     */
    public static final Eventrecorder EVENTRECORDER = Eventrecorder.EVENTRECORDER;

    /**
     * The table <code>localsoccer.eventsrecorder_events</code>.
     */
    public static final EventsrecorderEvents EVENTSRECORDER_EVENTS = EventsrecorderEvents.EVENTSRECORDER_EVENTS;

    /**
     * The table <code>localsoccer.fans</code>.
     */
    public static final Fans FANS = Fans.FANS;

    /**
     * The table <code>localsoccer.foul</code>.
     */
    public static final Foul FOUL = Foul.FOUL;

    /**
     * The table <code>localsoccer.goal</code>.
     */
    public static final Goal GOAL = Goal.GOAL;

    /**
     * The table <code>localsoccer.injury</code>.
     */
    public static final Injury INJURY = Injury.INJURY;

    /**
     * The table <code>localsoccer.league</code>.
     */
    public static final League LEAGUE = League.LEAGUE;

    /**
     * The table <code>localsoccer.match</code>.
     */
    public static final Match MATCH = Match.MATCH;

    /**
     * The table <code>localsoccer.match_referee</code>.
     */
    public static final MatchReferee MATCH_REFEREE = MatchReferee.MATCH_REFEREE;

    /**
     * The table <code>localsoccer.matching policy</code>.
     */
    public static final MatchingPolicy MATCHING_POLICY = MatchingPolicy.MATCHING_POLICY;

    /**
     * The table <code>localsoccer.offside</code>.
     */
    public static final Offside OFFSIDE = Offside.OFFSIDE;

    /**
     * The table <code>localsoccer.owner_manager_assignings</code>.
     */
    public static final OwnerManagerAssignings OWNER_MANAGER_ASSIGNINGS = OwnerManagerAssignings.OWNER_MANAGER_ASSIGNINGS;

    /**
     * The table <code>localsoccer.owner_owner_assignings</code>.
     */
    public static final OwnerOwnerAssignings OWNER_OWNER_ASSIGNINGS = OwnerOwnerAssignings.OWNER_OWNER_ASSIGNINGS;

    /**
     * The table <code>localsoccer.owner_teams</code>.
     */
    public static final OwnerTeams OWNER_TEAMS = OwnerTeams.OWNER_TEAMS;

    /**
     * The table <code>localsoccer.owners_of_stadium</code>.
     */
    public static final OwnersOfStadium OWNERS_OF_STADIUM = OwnersOfStadium.OWNERS_OF_STADIUM;

    /**
     * all posts of username
     */
    public static final PagePost PAGE_POST = PagePost.PAGE_POST;

    /**
     * The table <code>localsoccer.pages</code>.
     */
    public static final Pages PAGES = Pages.PAGES;

    /**
     * The table <code>localsoccer.players</code>.
     */
    public static final Players PLAYERS = Players.PLAYERS;

    /**
     * The table <code>localsoccer.previous_games_in_stadium</code>.
     */
    public static final PreviousGamesInStadium PREVIOUS_GAMES_IN_STADIUM = PreviousGamesInStadium.PREVIOUS_GAMES_IN_STADIUM;

    /**
     * The table <code>localsoccer.rankingpolicy</code>.
     */
    public static final Rankingpolicy RANKINGPOLICY = Rankingpolicy.RANKINGPOLICY;

    /**
     * The table <code>localsoccer.redcard</code>.
     */
    public static final Redcard REDCARD = Redcard.REDCARD;

    /**
     * The table <code>localsoccer.referee_matches</code>.
     */
    public static final RefereeMatches REFEREE_MATCHES = RefereeMatches.REFEREE_MATCHES;

    /**
     * The table <code>localsoccer.referees</code>.
     */
    public static final Referees REFEREES = Referees.REFEREES;

    /**
     * The table <code>localsoccer.season_matches</code>.
     */
    public static final SeasonMatches SEASON_MATCHES = SeasonMatches.SEASON_MATCHES;

    /**
     * The table <code>localsoccer.season_referee</code>.
     */
    public static final SeasonReferee SEASON_REFEREE = SeasonReferee.SEASON_REFEREE;

    /**
     * The table <code>localsoccer.season_tableleague</code>.
     */
    public static final SeasonTableleague SEASON_TABLELEAGUE = SeasonTableleague.SEASON_TABLELEAGUE;

    /**
     * The table <code>localsoccer.season_teams</code>.
     */
    public static final SeasonTeams SEASON_TEAMS = SeasonTeams.SEASON_TEAMS;

    /**
     * The table <code>localsoccer.seasons</code>.
     */
    public static final Seasons SEASONS = Seasons.SEASONS;

    /**
     * The table <code>localsoccer.stadium</code>.
     */
    public static final Stadium STADIUM = Stadium.STADIUM;

    /**
     * The table <code>localsoccer.subscribers</code>.
     */
    public static final Subscribers SUBSCRIBERS = Subscribers.SUBSCRIBERS;

    /**
     * The table <code>localsoccer.substitute</code>.
     */
    public static final Substitute SUBSTITUTE = Substitute.SUBSTITUTE;

    /**
     * The table <code>localsoccer.team_players</code>.
     */
    public static final TeamPlayers TEAM_PLAYERS = TeamPlayers.TEAM_PLAYERS;

    /**
     * The table <code>localsoccer.teammanagers</code>.
     */
    public static final Teammanagers TEAMMANAGERS = Teammanagers.TEAMMANAGERS;

    /**
     * The table <code>localsoccer.teamowner_ownereligible</code>.
     */
    public static final TeamownerOwnereligible TEAMOWNER_OWNERELIGIBLE = TeamownerOwnereligible.TEAMOWNER_OWNERELIGIBLE;

    /**
     * The table <code>localsoccer.teams</code>.
     */
    public static final Teams TEAMS = Teams.TEAMS;

    /**
     * all teams pending approval
     */
    public static final UnconfirmedTeams UNCONFIRMED_TEAMS = UnconfirmedTeams.UNCONFIRMED_TEAMS;

    /**
     * The table <code>localsoccer.yellowcard</code>.
     */
    public static final Yellowcard YELLOWCARD = Yellowcard.YELLOWCARD;
}
