/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables;


import dataLayer.Tables.Keys;
import dataLayer.Tables.Localsoccer;
import dataLayer.Tables.tables.records.FansRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fans extends TableImpl<FansRecord> {

    private static final long serialVersionUID = 34716850;

    /**
     * The reference instance of <code>localsoccer.fans</code>
     */
    public static final Fans FANS = new Fans();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FansRecord> getRecordType() {
        return FansRecord.class;
    }

    /**
     * The column <code>localsoccer.fans.fanID</code>.
     */
    public final TableField<FansRecord, String> FANID = createField(DSL.name("fanID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>localsoccer.fans</code> table reference
     */
    public Fans() {
        this(DSL.name("fans"), null);
    }

    /**
     * Create an aliased <code>localsoccer.fans</code> table reference
     */
    public Fans(String alias) {
        this(DSL.name(alias), FANS);
    }

    /**
     * Create an aliased <code>localsoccer.fans</code> table reference
     */
    public Fans(Name alias) {
        this(alias, FANS);
    }

    private Fans(Name alias, Table<FansRecord> aliased) {
        this(alias, aliased, null);
    }

    private Fans(Name alias, Table<FansRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Fans(Table<O> child, ForeignKey<O, FansRecord> key) {
        super(child, key, FANS);
    }

    @Override
    public Schema getSchema() {
        return Localsoccer.LOCALSOCCER;
    }

    @Override
    public UniqueKey<FansRecord> getPrimaryKey() {
        return Keys.KEY_FANS_PRIMARY;
    }

    @Override
    public List<UniqueKey<FansRecord>> getKeys() {
        return Arrays.<UniqueKey<FansRecord>>asList(Keys.KEY_FANS_PRIMARY);
    }

    @Override
    public List<ForeignKey<FansRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FansRecord, ?>>asList(Keys.FK_FANS_SUBSCRIBERS);
    }

    public Subscribers subscribers() {
        return new Subscribers(this, Keys.FK_FANS_SUBSCRIBERS);
    }

    @Override
    public Fans as(String alias) {
        return new Fans(DSL.name(alias), this);
    }

    @Override
    public Fans as(Name alias) {
        return new Fans(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fans rename(String name) {
        return new Fans(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fans rename(Name name) {
        return new Fans(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
