/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables;


import dataLayer.Tables.Demodb;
import dataLayer.Tables.Indexes;
import dataLayer.Tables.Keys;
import dataLayer.Tables.tables.records.InjuryRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Injury extends TableImpl<InjuryRecord> {

    private static final long serialVersionUID = -1478060363;

    /**
     * The reference instance of <code>demodb.injury</code>
     */
    public static final Injury INJURY = new Injury();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InjuryRecord> getRecordType() {
        return InjuryRecord.class;
    }

    /**
     * The column <code>demodb.injury.MatchID</code>.
     */
    public final TableField<InjuryRecord, Integer> MATCHID = createField(DSL.name("MatchID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>demodb.injury.EventID</code>.
     */
    public final TableField<InjuryRecord, Integer> EVENTID = createField(DSL.name("EventID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>demodb.injury.Time</code>.
     */
    public final TableField<InjuryRecord, String> TIME = createField(DSL.name("Time"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>demodb.injury.PlayerInjuredID</code>.
     */
    public final TableField<InjuryRecord, String> PLAYERINJUREDID = createField(DSL.name("PlayerInjuredID"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>demodb.injury</code> table reference
     */
    public Injury() {
        this(DSL.name("injury"), null);
    }

    /**
     * Create an aliased <code>demodb.injury</code> table reference
     */
    public Injury(String alias) {
        this(DSL.name(alias), INJURY);
    }

    /**
     * Create an aliased <code>demodb.injury</code> table reference
     */
    public Injury(Name alias) {
        this(alias, INJURY);
    }

    private Injury(Name alias, Table<InjuryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Injury(Name alias, Table<InjuryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Injury(Table<O> child, ForeignKey<O, InjuryRecord> key) {
        super(child, key, INJURY);
    }

    @Override
    public Schema getSchema() {
        return Demodb.DEMODB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INJURY_MATCHID);
    }

    @Override
    public List<ForeignKey<InjuryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InjuryRecord, ?>>asList(Keys.FK_INJURY_MATCH, Keys.FK_INJURY_PLAYERS);
    }

    public Match match() {
        return new Match(this, Keys.FK_INJURY_MATCH);
    }

    public Players players() {
        return new Players(this, Keys.FK_INJURY_PLAYERS);
    }

    @Override
    public Injury as(String alias) {
        return new Injury(DSL.name(alias), this);
    }

    @Override
    public Injury as(Name alias) {
        return new Injury(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Injury rename(String name) {
        return new Injury(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Injury rename(Name name) {
        return new Injury(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
