/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.tables;


import dataLayer.Tables.Demodb;
import dataLayer.Tables.Keys;
import dataLayer.Tables.tables.records.MatchFollowersRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchFollowers extends TableImpl<MatchFollowersRecord> {

    private static final long serialVersionUID = 1342198628;

    /**
     * The reference instance of <code>demodb.match_followers</code>
     */
    public static final MatchFollowers MATCH_FOLLOWERS = new MatchFollowers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MatchFollowersRecord> getRecordType() {
        return MatchFollowersRecord.class;
    }

    /**
     * The column <code>demodb.match_followers.matchID</code>.
     */
    public final TableField<MatchFollowersRecord, Integer> MATCHID = createField(DSL.name("matchID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>demodb.match_followers.followerID</code>.
     */
    public final TableField<MatchFollowersRecord, String> FOLLOWERID = createField(DSL.name("followerID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>demodb.match_followers</code> table reference
     */
    public MatchFollowers() {
        this(DSL.name("match_followers"), null);
    }

    /**
     * Create an aliased <code>demodb.match_followers</code> table reference
     */
    public MatchFollowers(String alias) {
        this(DSL.name(alias), MATCH_FOLLOWERS);
    }

    /**
     * Create an aliased <code>demodb.match_followers</code> table reference
     */
    public MatchFollowers(Name alias) {
        this(alias, MATCH_FOLLOWERS);
    }

    private MatchFollowers(Name alias, Table<MatchFollowersRecord> aliased) {
        this(alias, aliased, null);
    }

    private MatchFollowers(Name alias, Table<MatchFollowersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> MatchFollowers(Table<O> child, ForeignKey<O, MatchFollowersRecord> key) {
        super(child, key, MATCH_FOLLOWERS);
    }

    @Override
    public Schema getSchema() {
        return Demodb.DEMODB;
    }

    @Override
    public List<ForeignKey<MatchFollowersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MatchFollowersRecord, ?>>asList(Keys.FK__MATCH5, Keys.FK__SUBSCRIBERS7);
    }

    public Match match() {
        return new Match(this, Keys.FK__MATCH5);
    }

    public Subscribers subscribers() {
        return new Subscribers(this, Keys.FK__SUBSCRIBERS7);
    }

    @Override
    public MatchFollowers as(String alias) {
        return new MatchFollowers(DSL.name(alias), this);
    }

    @Override
    public MatchFollowers as(Name alias) {
        return new MatchFollowers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MatchFollowers rename(String name) {
        return new MatchFollowers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MatchFollowers rename(Name name) {
        return new MatchFollowers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
