/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CoachesTraining implements EnumType {

    GENERAL("GENERAL"),

    GK("GK"),

    FITNESS("FITNESS");

    private final String literal;

    private CoachesTraining(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "coaches_training";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
