/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PlayersFieldjob implements EnumType {

    GK("GK"),

    LB("LB"),

    RB("RB"),

    DM("DM"),

    CM("CM"),

    AM("AM"),

    LM("LM"),

    RM("RM"),

    CF("CF"),

    S("S");

    private final String literal;

    private PlayersFieldjob(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "players_fieldJob";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
