/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum RefereesRoleref implements EnumType {

    MAIN("MAIN"),

    ASSISTANT("ASSISTANT");

    private final String literal;

    private RefereesRoleref(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "referees_roleRef";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
