/*
 * This file is generated by jOOQ.
 */
package dataLayer.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TeammanagersPermissions implements EnumType {

    FINANCE("FINANCE"),

    PLAYERORIENTED("PLAYERORIENTED"),

    COACHORIENTED("COACHORIENTED"),

    GENERAL("GENERAL");

    private final String literal;

    private TeammanagersPermissions(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "teammanagers_permissions";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
