package dataLayer;

public enum SUBSCRIBERSUPDATES {

    ADDTEAMTOOWNER,
    ADMINSETAPPROVED,
    ARSETAPPROVED,
    SETTEAMTOPLAYER,
    SETTEAMTOTM,
    SETSUBSCRIBERNAME,
    SETPLAYERBIRTHDATE,
    SETPLAYERFIELDJOB,
    SETPLAYERSALARY,
    SETSUBSCRIBERPASSWORD,
    SETTMSALARY,
    SETTMPERMISSIONS,
    ADDMANAGERTOOWNER,
    DELETEMANAGERFROMOWNER,
    ADDOWNERTOOWNER,
    SETPLAYERELIGIBLE,
    SETCOACHELIGIBLE,
    SETTMELIGIBLE,
    REMOVEOWNER,
    DELETEOWNERFROMOWNER,
    ALLREFS
}
