package dataLayer;

public enum SUBSCRIBERSUPDATES {

    ADDTEAMTOOWNER,
    ADMINSETAPPROVED,
    ARSETAPPROVED,
    SETTEAMTOPLAYER,
    SETTEAMTOTM,
    SETSUBSCRIBERNAME,
    SETPLAYERBIRTHDATE,
    SETPLAYERFIELDJOB,
    SETPLAYERSALARY,
    SETTMSALARY,
    SETTMPERMISSIONS,
    ADDMANAGERTOOWNER,
    DELETEMANAGERFROMOWNER,
    ADDOWNERTOOWNER,
    DELETEOWNERFROMOWNER,
}
