package dataLayer;

public enum TEAMUPDATES {
    SETACTIVE,
    ADDPLAYER,
    ADDOWNER,
    ADDSTADIUM,
    ADDCOACH,
    SETTEAMMANAGER,
    ALLTEAMS,
    UNCONONFIRMED,
    TEAMOFOWNER,
    ONLYNOTACTIVE,
    ONLYACTIVE,
    TEAMSOFSEASON;
}
